"""fix moving_duration

Revision ID: 0b3973dab5df
Revises: 226de10ca77b
Create Date: 2026-07-03 15:28:05.025344

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from verve_backend.core.config import settings

# revision identifiers, used by Alembic.
revision: str = "0b3973dab5df"
down_revision: Union[str, Sequence[str], None] = "226de10ca77b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    schema = settings.POSTGRES_SCHEMA
    conn = op.get_bind()
    conn.execute(
        sa.text(
            f"UPDATE {schema}.activities "
            "SET moving_duration = NULL "
            "WHERE distance IS NULL AND moving_duration IS NOT NULL"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
