"""Add segment sets

Revision ID: 0b53ce351e8e
Revises: db3a6fcec306
Create Date: 2026-04-28 07:52:07.898075

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op
from verve_backend.core.config import settings

# revision identifiers, used by Alembic.
revision: str = "0b53ce351e8e"
down_revision: Union[str, Sequence[str], None] = "db3a6fcec306"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "segment_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "user_id", name="uix_segment_sets_id_user_id"),
    )
    op.create_index(
        op.f("ix_segment_sets_activity_id"),
        "segment_sets",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_segment_sets_user_id"), "segment_sets", ["user_id"], unique=False
    )
    op.create_table(
        "segment_cuts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("set_id", sa.Uuid(), nullable=False),
        sa.Column("point_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["set_id", "user_id"],
            ["segment_sets.id", "segment_sets.user_id"],
            name="fk_segment_cuts_set_id_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("set_id", "point_id", name="uix_segment_cuts_set_point"),
    )
    op.create_index(
        op.f("ix_segment_cuts_set_id"), "segment_cuts", ["set_id"], unique=False
    )
    op.create_index(
        op.f("ix_segment_cuts_user_id"), "segment_cuts", ["user_id"], unique=False
    )
    schema = settings.POSTGRES_SCHEMA

    # Backfill one default segment set per existing activity whose imported
    # track already has multiple source segments. The cut is the last point of
    # each source segment except the final segment.
    op.execute(f"""
        WITH segmented_activities AS (
            SELECT
                user_id,
                activity_id
            FROM {schema}.track_points
            GROUP BY user_id, activity_id
            HAVING COUNT(DISTINCT segment_id) > 1
        ),
        inserted_sets AS (
            INSERT INTO {schema}.segment_sets (
                id,
                user_id,
                activity_id,
                name
            )
            SELECT
                uuidv7(),
                user_id,
                activity_id,
                'Raw track segments'
            FROM segmented_activities
            RETURNING id, user_id, activity_id
        ),
        segment_ends AS (
            SELECT
                tp.user_id,
                tp.activity_id,
                tp.segment_id,
                MAX(tp.id) AS point_id,
                MAX(tp.segment_id) OVER (
                    PARTITION BY tp.user_id, tp.activity_id
                ) AS last_segment_id
            FROM {schema}.track_points tp
            JOIN segmented_activities sa
              ON sa.user_id = tp.user_id
             AND sa.activity_id = tp.activity_id
            GROUP BY
                tp.user_id,
                tp.activity_id,
                tp.segment_id
        )
        INSERT INTO {schema}.segment_cuts (
            user_id,
            set_id,
            point_id
        )
        SELECT
            se.user_id,
            ins.id,
            se.point_id
        FROM segment_ends se
        JOIN inserted_sets ins
          ON ins.user_id = se.user_id
         AND ins.activity_id = se.activity_id
        WHERE se.segment_id < se.last_segment_id
        ORDER BY
            se.user_id,
            se.activity_id,
            se.segment_id
    """)

    for prefix, table in [
        ("segment_set", "segment_sets"),
        ("segment_cut", "segment_cuts"),
    ]:
        op.execute(f"ALTER TABLE {schema}.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY {prefix}_isolation_policy ON {schema}.{table}
            FOR ALL USING (user_id = current_setting('verve_user.curr_user')::uuid)
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_segment_cuts_user_id"), table_name="segment_cuts")
    op.drop_index(op.f("ix_segment_cuts_set_id"), table_name="segment_cuts")
    op.drop_table("segment_cuts")
    op.drop_index(op.f("ix_segment_sets_user_id"), table_name="segment_sets")
    op.drop_index(op.f("ix_segment_sets_activity_id"), table_name="segment_sets")
    op.drop_table("segment_sets")
    # ### end Alembic commands ###
