"""Add collections

Revision ID: 226de10ca77b
Revises: c3378badd2f4
Create Date: 2026-07-01 10:16:29.500212

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op
from verve_backend.core.config import settings

# revision identifiers, used by Alembic.
revision: str = "226de10ca77b"
down_revision: Union[str, Sequence[str], None] = "c3378badd2f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_collections",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_collections_user_id"),
        "activity_collections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "activity_collection_links",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["activity_collections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("activity_id", "collection_id"),
    )
    schema = settings.POSTGRES_SCHEMA
    for prefix, table in [
        ("activity_collection", "activity_collections"),
    ]:
        op.execute(f"ALTER TABLE {schema}.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY {prefix}_isolation_policy ON {schema}.{table}
            FOR ALL USING (user_id = current_setting('verve_user.curr_user')::uuid)
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity_collection_links")
    op.drop_index(
        op.f("ix_activity_collections_user_id"), table_name="activity_collections"
    )
    op.drop_table("activity_collections")
    # ### end Alembic commands ###
