"""Initial structure

Revision ID: 3bd7d8987ff0
Revises:
Create Date: 2025-12-25 10:00:47.451851

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op
from verve_backend.core.config import settings

# revision identifiers, used by Alembic.
revision: str = "3bd7d8987ff0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    schema = settings.POSTGRES_SCHEMA
    """Upgrade schema."""
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.execute("DROP TYPE IF EXISTS distancerequirement CASCADE")
    op.execute("DROP TYPE IF EXISTS goaltype CASCADE")
    op.execute("DROP TYPE IF EXISTS equipmenttype CASCADE")

    op.execute("DROP TYPE IF EXISTS temporaltype CASCADE")
    op.execute("DROP TYPE IF EXISTS goaltype CASCADE")
    op.execute("DROP TYPE IF EXISTS goalaggregation CASCADE")
    op.execute("DROP TYPE IF EXISTS supportedlocale CASCADE")
    op.execute("DROP TYPE IF EXISTS highlightmetric CASCADE")
    op.execute("DROP TYPE IF EXISTS highlighttimescope CASCADE")

    op.execute(f"GRANT USAGE ON SCHEMA {schema} TO verve_user")
    op.execute(
        f"ALTER DEFAULT PRIVILEGES IN SCHEMA {schema} GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO verve_user"  # noqa: E501
    )
    op.execute(
        f"ALTER DEFAULT PRIVILEGES IN SCHEMA {schema} GRANT USAGE ON SEQUENCES TO verve_user"  # noqa: E501
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_type",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "distance_requirement",
            sa.Enum(
                "REQUIRED", "OPTIONAL", "NOT_APPLICABLE", name="distancerequirement"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "equipment",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "equipment_type",
            sa.Enum(
                "BIKE",
                "SHOES",
                "SKIS",
                "SNOWBOARD",
                "HOMETRAINER",
                name="equipmenttype",
            ),
            nullable=False,
        ),
        sa.Column("brand", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("purchase_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "equipment_sets",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "goals",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("current", sa.Float(), nullable=False),
        sa.Column("target", sa.Float(), nullable=False),
        sa.Column("current_updated", sa.DateTime(), nullable=True),
        sa.Column("upper_bound", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "temporal_type",
            sa.Enum("YEARLY", "MONTHLY", "WEEKLY", name="temporaltype"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("week", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("ACTIVITY", "MANUAL", "LOCATION", name="goaltype"),
            nullable=False,
        ),
        sa.Column(
            "aggregation",
            sa.Enum(
                "COUNT",
                "TOTAL_DISTANCE",
                "AVG_DISTANCE",
                "MAX_DISTANCE",
                "DURATION",
                name="goalaggregation",
            ),
            nullable=False,
        ),
        sa.Column("constraints", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "locations",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "loc",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sub_activity_type",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["activity_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "type_id", name="uix_subactivity_name_type_id"),
    )
    op.create_table(
        "zone_intervals",
        sa.Column("metric", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start", sa.Float(), nullable=True),
        sa.Column("end", sa.Float(), nullable=True),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activities",
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("duration", sa.Interval(), nullable=False),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("moving_duration", sa.Interval(), nullable=True),
        sa.Column("elevation_change_up", sa.Float(), nullable=True),
        sa.Column("elevation_change_down", sa.Float(), nullable=True),
        sa.Column("avg_speed", sa.Float(), nullable=True),
        sa.Column("avg_heartrate", sa.Float(), nullable=True),
        sa.Column("avg_power", sa.Float(), nullable=True),
        sa.Column("max_speed", sa.Float(), nullable=True),
        sa.Column("max_heartrate", sa.Float(), nullable=True),
        sa.Column("max_power", sa.Float(), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("sub_type_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sub_type_id"],
            ["sub_activity_type.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "default_equipment_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("set_id", sa.Uuid(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("sub_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["set_id"], ["equipment_sets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["sub_type_id"],
            ["sub_activity_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["activity_type.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_default_equipment_sets_type_sub_type",
        "default_equipment_sets",
        ["type_id", "sub_type_id"],
        unique=False,
    )
    op.create_table(
        "equipment_set_links",
        sa.Column("set_id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["set_id"], ["equipment_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("set_id", "equipment_id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("default_type_id", sa.Integer(), nullable=False),
        sa.Column("defautl_sub_type_id", sa.Integer(), nullable=True),
        sa.Column(
            "locale", sa.Enum("DE", "EN", name="supportedlocale"), nullable=False
        ),
        sa.Column("heatmap_settings", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_type_id"],
            ["activity_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["defautl_sub_type_id"],
            ["sub_activity_type.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "activity_equipment",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("activity_id", "equipment_id"),
    )
    op.create_table(
        "activity_highlights",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column(
            "metric",
            sa.Enum(
                "DURATION",
                "DISTANCE",
                "ELEVATION_CHANGE_UP",
                "AVG_SPEED",
                "AVG_POWER",
                "MAX_SPEED",
                "MAX_POWER",
                "AVG_POWER1MIN",
                "AVG_POWER2MIN",
                "AVG_POWER5MIN",
                "AVG_POWER10MIN",
                "AVG_POWER20MIN",
                "AVG_POWER30MIN",
                "AVG_POWER60MIN",
                name="highlightmetric",
            ),
            nullable=False,
        ),
        sa.Column(
            "scope",
            sa.Enum("YEARLY", "LIFETIME", name="highlighttimescope"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "metric",
            "scope",
            "year",
            "rank",
            "type_id",
            name="uix_highlight_rank",
        ),
    )
    op.create_index(
        op.f("ix_activity_highlights_user_id"),
        "activity_highlights",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "image",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_image_activity_id"), "image", ["activity_id"], unique=False
    )
    op.create_index(op.f("ix_image_user_id"), "image", ["user_id"], unique=False)
    op.create_table(
        "raw_track_data",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("store_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("activity_id"),
    )
    op.create_index(
        op.f("ix_raw_track_data_user_id"), "raw_track_data", ["user_id"], unique=False
    )
    op.create_table(
        "track_points",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column(
            "geography",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("elevation", sa.Float(), nullable=True),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("heartrate", sa.Integer(), nullable=True),
        sa.Column("cadence", sa.Integer(), nullable=True),
        sa.Column("power", sa.Integer(), nullable=True),
        sa.Column("extensions", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "activity_id", "user_id"),
        sa.UniqueConstraint(
            "id", "activity_id", name="uix_track_points_id_activity_id"
        ),
    )
    op.create_index(
        "idx_track_points_activity_segment",
        "track_points",
        ["activity_id", "segment_id"],
        unique=False,
    )
    op.create_index(
        "idx_track_points_user_activity",
        "track_points",
        ["user_id", "activity_id"],
        unique=False,
    )

    for prefix, table in [
        ("activity", "activities"),
        ("activity_highlights", "activity_highlights"),
        ("track_point", "track_points"),
        ("goal", "goals"),
        ("raw_track_data", "raw_track_data"),
        ("image", "image"),
        ("user_setting", "user_settings"),
        ("zone_interval", "zone_intervals"),
        ("equipment", "equipment"),
        ("equipment_set", "equipment_sets"),
        ("default_equipment_set", "default_equipment_sets"),
        ("location", "locations"),
    ]:
        op.execute(f"ALTER TABLE {schema}.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY {prefix}_isolation_policy ON {schema}.{table}
            FOR ALL USING (user_id = current_setting('verve_user.curr_user')::uuid)
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alembic_version",
        sa.Column(
            "version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
    )
    op.drop_index("idx_track_points_user_activity", table_name="track_points")
    op.drop_index(
        "idx_track_points_geometry", table_name="track_points", postgresql_using="gist"
    )
    op.drop_index(
        "idx_track_points_geography", table_name="track_points", postgresql_using="gist"
    )
    op.drop_index("idx_track_points_activity_segment", table_name="track_points")
    op.drop_table("track_points")
    op.drop_index(op.f("ix_raw_track_data_user_id"), table_name="raw_track_data")
    op.drop_table("raw_track_data")
    op.drop_index(op.f("ix_image_user_id"), table_name="image")
    op.drop_index(op.f("ix_image_activity_id"), table_name="image")
    op.drop_table("image")
    op.drop_index(
        op.f("ix_activity_highlights_user_id"), table_name="activity_highlights"
    )
    op.drop_table("activity_highlights")
    op.drop_table("activity_equipment")
    op.drop_table("user_settings")
    op.drop_table("equipment_set_links")
    op.drop_index(
        "idx_default_equipment_sets_type_sub_type", table_name="default_equipment_sets"
    )
    op.drop_table("default_equipment_sets")
    op.drop_table("activities")
    op.drop_table("zone_intervals")
    op.drop_table("sub_activity_type")
    op.drop_index("idx_locations_loc", table_name="locations", postgresql_using="gist")
    op.drop_table("locations")
    op.drop_table("goals")
    op.drop_table("equipment_sets")
    op.drop_table("equipment")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("activity_type")
    op.execute("DROP EXTENSION IF EXISTS postgis")
    op.execute("DROP SCHEMA IF EXISTS verve")
