"""Add activity tag and tag categories and name search extensions

Revision ID: 5e40e7670600
Revises: ee9fb2271c6d
Create Date: 2026-03-16 12:23:29.751453

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e40e7670600"
down_revision: Union[str, Sequence[str], None] = "ee9fb2271c6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DEFAULT_TAG_CATEGORIES: list[str] = ["Workout"]
DEFAULT_TAGS: list[tuple[str, str | None]] = [
    ("Interval", "Workout"),
    ("Endurance", "Workout"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS fuzzystrmatch")

    op.create_table(
        "activity_tag_categories",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "user_id", name="uix_tag_cat_name_user_id"),
    )
    op.create_index(
        "idx_activity_tag_cats_name_dm",
        "activity_tag_categories",
        [sa.literal_column("daitch_mokotoff(name)")],
        unique=False,
        postgresql_using="gin",
        postgresql_with={"fastupdate": "off"},
    )
    op.create_index(
        "idx_activity_tag_cats_name_gin_trgm",
        "activity_tag_categories",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_activity_tag_categories_user_id"),
        "activity_tag_categories",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "activity_tags",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["activity_tag_categories.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "user_id", "category_id", name="uix_tag_name_user_id_cat"
        ),
    )
    op.create_index(
        "idx_activity_tags_name_dm",
        "activity_tags",
        [sa.literal_column("daitch_mokotoff(name)")],
        unique=False,
        postgresql_using="gin",
        postgresql_with={"fastupdate": "off"},
    )
    op.create_index(
        "idx_activity_tags_name_gin_trgm",
        "activity_tags",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_activity_tags_user_id"), "activity_tags", ["user_id"], unique=False
    )
    op.create_table(
        "activity_tag_links",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["activity_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("activity_id", "tag_id"),
    )

    op.create_foreign_key(
        "fk_activities_type_id", "activities", "activity_type", ["type_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_activity_highlights_type_id",
        "activity_highlights",
        "activity_type",
        ["type_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_locations_sub_type_id",
        "locations",
        "location_sub_type",
        ["sub_type_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_locations_type_id", "locations", "location_type", ["type_id"], ["id"]
    )
    conn = op.get_bind()

    user_ids = [
        row[0] for row in conn.execute(sa.text("SELECT id FROM users")).fetchall()
    ]

    for user_id in user_ids:
        # Insert categories, capturing the generated id for each
        category_ids: dict[str, int] = {}
        for category_name in DEFAULT_TAG_CATEGORIES:
            result = conn.execute(
                sa.text("""
                    INSERT INTO activity_tag_categories (name, user_id)
                    VALUES (:name, :user_id)
                    ON CONFLICT ON CONSTRAINT uix_tag_cat_name_user_id DO UPDATE
                        SET name = EXCLUDED.name
                    RETURNING id
                """),
                {"name": category_name, "user_id": user_id},
            )
            category_ids[category_name] = result.scalar_one()

        # Insert tags, resolving category name → id
        for tag_name, category_name in DEFAULT_TAGS:
            conn.execute(
                sa.text("""
                    INSERT INTO activity_tags (name, user_id, category_id)
                    VALUES (:name, :user_id, :category_id)
                    ON CONFLICT ON CONSTRAINT uix_tag_name_user_id_cat DO NOTHING
                """),
                {
                    "name": tag_name,
                    "user_id": user_id,
                    "category_id": category_ids.get(category_name),
                },
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_locations_type_id", "locations", type_="foreignkey")
    op.drop_constraint("fk_locations_sub_type_id", "locations", type_="foreignkey")
    op.drop_constraint(
        "fk_activity_highlights_type_id", "activity_highlights", type_="foreignkey"
    )
    op.drop_constraint("fk_activities_type_id", "activities", type_="foreignkey")
    op.drop_table("activity_tag_links")
    op.drop_index(op.f("ix_activity_tags_user_id"), table_name="activity_tags")
    op.drop_index(
        "idx_activity_tags_name_gin_trgm",
        table_name="activity_tags",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_activity_tags_name_dm",
        table_name="activity_tags",
        postgresql_using="gin",
        postgresql_with={"fastupdate": "off"},
    )
    op.drop_table("activity_tags")
    op.drop_index(
        op.f("ix_activity_tag_categories_user_id"), table_name="activity_tag_categories"
    )
    op.drop_index(
        "idx_activity_tag_cats_name_gin_trgm",
        table_name="activity_tag_categories",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_activity_tag_cats_name_dm",
        table_name="activity_tag_categories",
        postgresql_using="gin",
        postgresql_with={"fastupdate": "off"},
    )
    op.drop_table("activity_tag_categories")
    # Drop extensions last — only safe if nothing else in the DB uses them
    # ### end Alembic commands ###
