"""Add climbing activities

Revision ID: 98b8bfa023e7
Revises: f385499f76d8
Create Date: 2026-01-23 22:12:53.812585

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98b8bfa023e7"
down_revision: Union[str, Sequence[str], None] = "f385499f76d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    # 1. Insert 'Climbing' activity type (do nothing if it exists)
    bind.execute(
        sa.text(
            """
            INSERT INTO activity_type (name, distance_requirement)
            VALUES ('Climbing', 'OPTIONAL')
            ON CONFLICT (name) DO NOTHING
            """
        )
    )

    # 2. Get the Climbing activity type ID
    res = bind.execute(sa.text("SELECT id FROM activity_type WHERE name = 'Climbing'"))
    climbing_id = res.scalar()

    if climbing_id is not None:
        # 3. Insert climbing sub-types safely (do nothing if they exist)
        climbing_subtypes = [
            "Bouldering",
            "Sport Climbing",
            "Indoor Climbing",
            "Outdoor Climbing",
        ]

        for subtype in climbing_subtypes:
            bind.execute(
                sa.text(
                    """
                    INSERT INTO sub_activity_type (name, type_id)
                    VALUES (:name, :type_id)
                    ON CONFLICT (name, type_id) DO NOTHING
                    """
                ),
                {"name": subtype, "type_id": climbing_id},
            )
    res = bind.execute(sa.text("SELECT id FROM activity_type WHERE name = 'Other'"))
    other_id = res.scalar()

    if other_id is not None:
        bind.execute(
            sa.text(
                """
                DELETE FROM sub_activity_type
                WHERE type_id = :type_id AND name = 'Climbing'
                """
            ),
            {"type_id": other_id},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    # 1. Get the Climbing activity type ID
    res = bind.execute(sa.text("SELECT id FROM activity_type WHERE name = 'Climbing'"))
    climbing_id = res.scalar()

    if climbing_id is not None:
        # 2. Delete all climbing sub-types
        bind.execute(
            sa.text("DELETE FROM sub_activity_type WHERE type_id = :type_id"),
            {"type_id": climbing_id},
        )

    # 3. Delete the Climbing activity type
    bind.execute(sa.text("DELETE FROM activity_type WHERE name = 'Climbing'"))

    res = bind.execute(sa.text("SELECT id FROM activity_type WHERE name = 'Other'"))
    other_id = res.scalar()

    if other_id is not None:
        bind.execute(
            sa.text(
                """
                INSERT INTO sub_activity_type (name, type_id)
                VALUES ('Climbing', :type_id)
                ON CONFLICT (name, type_id) DO NOTHING
                """
            ),
            {"type_id": other_id},
        )
    # ### end Alembic commands ###
