"""Add records settings to user settings

Revision ID: c3378badd2f4
Revises: b7f4c2d9a8e1
Create Date: 2026-06-19 08:56:33.305495

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3378badd2f4"
down_revision: Union[str, Sequence[str], None] = "b7f4c2d9a8e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings",
        sa.Column("records_settings", sa.JSON(), nullable=True),
    )
    bind = op.get_bind()

    bind.execute(
        sa.text(
            "UPDATE user_settings "
            "SET records_settings = :value "
            "WHERE records_settings IS NULL"
        ),
        {"value": '{"default_activity_type": 1}'},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "records_settings")
    # ### end Alembic commands ###
