"""Add indices for location name query

Revision ID: db3a6fcec306
Revises: 5e40e7670600
Create Date: 2026-03-23 20:43:15.345552

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db3a6fcec306"
down_revision: Union[str, Sequence[str], None] = "5e40e7670600"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_locations_name_dm",
        "locations",
        [sa.literal_column("daitch_mokotoff(name)")],
        unique=False,
        postgresql_using="gin",
        postgresql_with={"fastupdate": "off"},
    )
    op.create_index(
        "idx_locations_name_gin_trgm",
        "locations",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_locations_name_gin_trgm",
        table_name="locations",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_locations_name_dm",
        table_name="locations",
        postgresql_using="gin",
        postgresql_with={"fastupdate": "off"},
    )
    # ### end Alembic commands ###
