"""Add location types

Revision ID: f46bdd18db9f
Revises: d36a17d3a987
Create Date: 2026-01-29 23:03:47.905280

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f46bdd18db9f"
down_revision: Union[str, Sequence[str], None] = "d36a17d3a987"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_type",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "location_sub_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["location_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "type_id", name="uix_sublocation_name_type_id"),
    )

    location_types = {
        "Nature & Adventure": [
            "Peak",
            "Mountain Pass",
            "Lake",
            "Alpine Hut",
            "Climbing Crag",
            "Trailhead",
            "Viewpoint",
        ],
        "Facilities": [
            "Gym",
            "Swimming Pool",
            "Climbing Gym",
            "Sports Center",
            "Ski Resort",
            "Bike Park",
            "Stadium",
        ],
        "Travel & Logistics": [
            "Train Station",
            "Bus Stop",
            "Parking",
            "Hotel / Lodging",
        ],
        "Personal": ["Home", "Work"],
        "Point of Interest": ["Landmark", "Other"],
    }

    bind = op.get_bind()
    for _type, sub_types in location_types.items():
        bind.execute(
            sa.text("""
            INSERT INTO location_type (name)
            VALUES (:name)
        """),
            {"name": _type},
        )
        for sub_name in sub_types:
            bind.execute(
                sa.text("""
                INSERT INTO location_sub_type (name, type_id)
                VALUES (
                    :sub_name,
                    (SELECT id FROM location_type WHERE name = :type_name)
                )
            """),
                {"sub_name": sub_name, "type_name": _type},
            )

    # Step 1: Add columns as nullable first
    op.add_column("locations", sa.Column("type_id", sa.Integer(), nullable=True))
    op.add_column("locations", sa.Column("sub_type_id", sa.Integer(), nullable=True))

    # Step 2: Set default values for existing rows
    op.execute(
        sa.text("""
        UPDATE locations SET
            type_id = (SELECT id FROM location_type WHERE name = 'Point of Interest'),
            sub_type_id = (SELECT id FROM location_sub_type WHERE name = 'Landmark')
        WHERE type_id IS NULL
        """)
    )

    # Step 3: Make columns non-nullable
    op.alter_column("locations", "type_id", nullable=False)
    op.alter_column("locations", "sub_type_id", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "sub_type_id")
    op.drop_column("locations", "type_id")
    op.drop_table("location_sub_type")
    op.drop_table("location_type")
    # ### end Alembic commands ###
